apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: api-connect-cluster
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-minimum
  namespace: cp4i
spec:
  license:
    license: L-RJON-C7BJ42
    accept: true
    use: nonproduction
  endpointTypes:
    - APIs
    - Events
  analytics:
    storage:
      enabled: true
      type: unique
  profile: n1xc7.m48
  version: 10.0.4.0
  storageClassName: ibmc-block-gold
