apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qm-alpha
  namespace:
spec:
  destination:
    namespace: mq
    server: https://kubernetes.default.svc
  project: mq
  source:
    repoURL: https://github.com/Martist/cp4i-gitops.git
    path: qm-alpha/resources
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
