apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ace-hello-world-prod
  annotations:
    argocd.argoproj.io/sync-wave: "400"
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: cp4i
  source:
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/cp4i-gitops 
    path: ace-apps/ace-integration-server-chart
    targetRevision: main
    helm:
      values: |
          image:
            repository: image-registry.openshift-image-registry.svc:5000/cp4i/ace-hello-world
            tag: a6f27d20eee62a64bd810d005550c95d37cc00db
          replicaCount: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: appconnect.ibm.com
    kind: IntegrationServer
    jsonPointers:
    - /spec/replicas
