apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-alpha-mqsc
data:
  qm-alpha.mqsc: |+
    *
    * setup queues
    *
    DEFINE QLOCAL(COMMANDS) REPLACE
    DEFINE QLOCAL(COMMANDS.COPY) REPLACE
    ALTER QLOCAL(COMMANDS) STREAMQ('COMMANDS.COPY') STRMQOS(MUSTDUP)
    *
    * setup channel
    *
    DEFINE CHANNEL(KAFKA.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) REPLACE
    SET CHLAUTH(KAFKA.SVRCONN) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
    *
    *setup LDAP
    * 
    DEFINE AUTHINFO(USE.LDAP) AUTHTYPE(IDPWLDAP) ADOPTCTX(YES) CONNAME('ldap-service.mq-ldap.svc.cluster.local(389)') CHCKCLNT(REQUIRED) CLASSGRP('groupOfUniqueNames') CLASSUSR('inetOrgPerson') FINDGRP('uniquemember') BASEDNG('ou=Groups,dc=local,dc=io') BASEDNU('ou=People,dc=local,dc=io') LDAPUSER('cn=admin,dc=local,dc=io') LDAPPWD('admin') SHORTUSR('sn') GRPFIELD('cn') USRFIELD('cn') AUTHORMD(SEARCHGRP) NESTGRP(YES)
    ALTER QMGR CONNAUTH(USE.LDAP)