apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-server-tls-alpha-letsencrypt
spec:
  secretName: mq-server-tls-alpha-letsencrypt
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: nbt.ceibm.com
  subject:
    organizations:
      - mq
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'qm-alpha-ibm-mq-qm-cp4i.cpi4i-classic-fra02-b3c-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud'
    - 'nbt.ceibm.com'
  issuerRef:
    name: letsencrypt-issuer
