kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acme-rb
subjects:
  - kind: ServiceAccount
    name: openshift-acme
    namespace: cp4i
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-acme
