apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ace-application
spec:
  finally:
    - name: github-set-status-finally
      params:
        - name: GITHUB_HOST_URL
          value: api.github.com
        - name: GITHUB_TOKEN_SECRET_NAME
          value: 'github-token'
        - name: GITHUB_TOKEN_SECRET_KEY
          value: 'token'
        - name: TARGET_URL
          value: >-
            https://console-openshift-console.itzroks-2700015rqr-7vz6mp-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-de.containers.appdomain.cloud/k8s/ns/cp4i/tekton.dev~v1beta1~PipelineRun/$(context.pipelineRun.name)
        - name: DESCRIPTION
          value: Integration server build finished
        - name: CONTEXT
          value: continuous-integration/tekton
        - name: STATE
          value: $(tasks.status)
        - name: SHA
          value: $(tasks.git-clone.results.commit)
        - name: REPO_FULL_NAME
          value: $(params.gitrepo)
      taskRef:
        kind: Task
        name: github-set-status
  params:
    - name: commit_id
      type: string
    - name: commit_message
      type: string
    - name: commit_user
      type: string
    - name: imageURL
      type: string
    - name: imageTag
      type: string
    - description: The git repo to clone
      name: gitrepo
      type: string
    - description: The name of the git repo to clone
      name: gitreponame
      type: string
    - description: The revision of the git repo to clone
      name: gitrevision
      type: string
    - default: .
      description: The path in the git repo to build from
      name: gitpath
      type: string
  tasks:
    - name: s2i-ace
      params:
        - name: PATH_CONTEXT
          value: app/$(params.gitpath)
        - name: TLSVERIFY
          value: 'false'
        - name: LICENSE
          value: accept
        - name: BUILD_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/cp4i/s2i-ace:12.0.6.0-r1
        - name: RUNTIME_IMAGE
          value: >-
            cp.icr.io/cp/appc/ace-server-prod@sha256:3dbcc7caa22b0b0e6a5467cbb1a6086fafa0e125682dee4d2f51b7a59cecc766
        - name: commit_id
          value: $(params.commit_id)
        - name: commit_message
          value: $(params.commit_message)
        - name: commit_user
          value: $(params.commit_user)
        - name: IMAGE
          value: '$(params.imageURL):$(params.imageTag)'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: s2i-ace-overlay
      workspaces:
        - name: source
          workspace: source
    - name: github-set-status
      params:
        - name: GITHUB_HOST_URL
          value: api.github.com
        - name: GITHUB_TOKEN_SECRET_NAME
          value: 'github-token'
        - name: GITHUB_TOKEN_SECRET_KEY
          value: 'token'
        - name: TARGET_URL
          value: >-
            https://console-openshift-console.itzroks-2700015rqr-7vz6mp-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-de.containers.appdomain.cloud/ns/cp4i/tekton.dev~v1beta1~PipelineRun/$(context.pipelineRun.name)
        - name: DESCRIPTION
          value: Integration server build is pending
        - name: CONTEXT
          value: continuous-integration/tekton
        - name: STATE
          value: pending
        - name: REPO_FULL_NAME
          value: $(params.gitrepo)
        - name: SHA
          value: $(tasks.git-clone.results.commit)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: github-set-status
    - name: git-clone
      params:
        - name: url
          value: $(params.gitrepo)
        - name: revision
          value: $(params.gitrevision)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: app
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:fbf1c4df0f6c1330b34a0ea882ca1dff0e224f3a7060772532a2244438b91074
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: git-basic-auth
  workspaces:
    - name: source
    - name: git-basic-auth
      optional: true

