kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s2i-ace-varlibcontainers-pvc
  namespace: cp4i
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ibmc-block-gold
