kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-workspace
  namespace: cp4i
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-file-gold-gid
  volumeMode: Filesystem
