apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-build-ace-application
spec:
  params:
    - name: git-revision
    - name: git-revision-short
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations: {}
        name: build-$(tt.params.git-repo-name)-$(tt.params.git-revision-short)
        labels:
          tekton.dev/pipeline: build-ace-application
      spec:
        params:
          - name: commit_id
            value: $(tt.params.git-revision)
          - name: commit_message
            value: $(tt.params.git-commit-message)
          - name: commit_user
            value: $(tt.params.pusher-name)
          - name: imageURL
            value: image-registry.openshift-image-registry.svc:5000/cp4i/$(tt.params.git-repo-name)
          - name: imageTag
            value: $(tt.params.git-revision)
          - name: gitrepo
            value: $(tt.params.git-repo-url)
          - name: gitreponame
            value: $(tt.params.git-repo-name)
          - name: gitrevision
            value: $(tt.params.git-revision)
          - name: gitpath
            value: .
          #- name: gitopsrepo
          #  value: https://github.com/Nordic-MVP-GitOps-Repos/cp4i-gitops
        pipelineRef:
          name: build-ace-application
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: tekton-workspace
