apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-alpha-configmap
data:
  tls.mqsc: |
    DEFINE QLOCAL('ALPHA.QUEUE1') DEFPSIST(YES) REPLACE 
    DEFINE CHANNEL(HAQMCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL('alpha.from.beta') CHLTYPE(RCVR) TRPTYPE(TCP) XMITQ('QMBETA') CONNAME('qm-beta-ibm-mq.cp4i.svc(1414)') 
    SET CHLAUTH(HAQMCHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)

