apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-alpha-configmap
data:
  tls.mqsc: |
    DEFINE QLOCAL('ALPHA.QUEUE1') DEFPSIST(YES) REPLACE 
    DEFINE QLOCAL('ALPHA.QUEUE2') DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('ALPHA.QUEUE3') DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('ALPHA.QUEUE4') DEFPSIST(YES) REPLACE
    DEFINE CHANNEL(HAQMCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(HAQMCHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)


    DEFINE QREMOTE(ALPHA.REMOTE) DESCR('REMOTE QUEUE FOR QMALPHA') REPLACE PUT(ENABLED) XMITQ(ALPHA.DETLA.TRANS)  RNAME(DELTA.LOCAL) RQMNAME(QMDELTA)

    DEFINE QLOCAL(ALPHA.DETLA.TRANS) DESCR('TRANSMISSION QUEUE TO DELTA') REPLACE USAGE(XMITQ) PUT(ENABLED) GET(ENABLED) TRIGGER TRIGTYPE(FIRST) TRIGDATA(ALPHA.TO.DELTA) INITQ(SYSTEM.CHANNEL.INITQ)

    DEFINE CHANNEL(ALPHA.TO.DELTA) CHLTYPE(SDR) TRPTYPE(TCP) REPLACE DESCR('SENDER CHANNEL TO DELTA') XMITQ(ALPHA.DETLA.TRANS) CONNAME('qm-delta-ibm-mq.cp4i.svc.cluster.local(1414)')
    START CHANNEL(ALPHA.TO.DELTA)
