apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-beta-configmap
data:
  tls.mqsc: |
    DEFINE QREMOTE ('ALPHA.QUEUE1') RNAME('ALPHA.QUEUE1') RQMNAME('QMALPHA') REPLACE
    DEFINE QLOCAL('BETA.QUEUE1') DEFPSIST(YES) REPLACE 
    DEFINE QLOCAL('BETA.QUEUE2') DEFPSIST(YES) REPLACE 
    DEFINE CHANNEL(HAQMCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(HAQMCHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
    DEFINE CHANNEL('beta.to.alpha') CHLTYPE(SDR) TRPTYPE(TCP) XMITQ('QMALPHA') CONNAME('qm-alpha-ibm-mq.cp4i.svc(1414)')
