apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-delta-configmap
data:
  mqsc: |
    DEFINE QLOCAL('DELTA.QUEUE.1') REPLACE
    DEFINE QLOCAL('DELTA.QUEUE.2') REPLACE
    DEFINE CHANNEL('GAMMA.DELTA') CHLTYPE(RCVR) TRPTYPE(TCP) XMITQ(GAMMA) CONNAME('qm-gamma-ibm-mq.cp4i.svc(1414)')
