apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-delta-configmap
data:
  mqsc: |
    DEFINE QLOCAL('DELTA_QUEUE_1') REPLACE
    DEFINE QLOCAL('DELTA_QUEUE_2') REPLACE
    DEFINE QLOCAL('TRANSMIT_TO_GAMMA') USAGE(XMITQ)
    DEFINE QREMOTE('REMOTE_ON_GAMMA') RNAME('GAMMA_QUEUE_1') RQMNAME('QMGAMMA') XMITQ('TRANSMIT_TO_GAMMA')    
    DEFINE CHANNEL('DELTA.GAMMA') CHLTYPE(SDR) TRPTYPE(TCP) XMITQ('TRANSMIT_TO_GAMMA') CONNAME('qm-gamma-ibm-mq.cp4i.svc(1414)')
    START CHANNEL('DELTA.GAMMA')
    DEFINE CHANNEL('GAMMA.DELTA') CHLTYPE(RCVR) TRPTYPE(TCP) REPLACE
    START CHANNEL('GAMMA.DELTA')
