apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-gamma-configmap
data:
  mqsc: |
    DEFINE QLOCAL('GAMMA.QUEUE.1') REPLACE
    DEFINE QLOCAL('GAMMA.QUEUE.2') REPLACE
    DEFINE CHANNEL('GAMMA.DELTA') CHLTYPE(SDR) TRPTYPE(TCP) XMITQ(DELTA) CONNAME('qm-delta-ibm-mq.cp4i.svc(1414)')
    
