kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mq-argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - mq.ibm.com
      - cert-manager.io
      - tekton.dev
      - build.openshift.io
      - image.openshift.io
      - route.openshift.io
      - triggers.tekton.dev
    resources:
      - '*'
