apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: mq
    server: https://kubernetes.default.svc
  project: mq
  source:
    repoURL: https://github.com/Martist/cp4i-gitops.git 
    path: namespaces/resources
    targetRevision: mq-setup
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
