apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operands
  annotations:
    argocd.argoproj.io/sync-wave: "300"
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: cp4i
  source:
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/cp4i-gitops 
    path: operands/resources
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
