resources:
  - config-map
  - new-qm.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patches/new-queue-patch.yaml
    target:
      kind: QueueManager
      name: new-qm
