apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myqm
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: cp4i
  source:
    repoURL: https://github.com/Martist/cp4i-gitops.git
    path: mq-instances/resources/myqm
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
